use_frameworks!

platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ZLHTTPSessionManager_Example' do
  pod 'ZLHTTPSessionManager', :path => '../'

  target 'ZLHTTPSessionManager_Tests' do
    inherit! :search_paths

    
  end
end
