use_frameworks!

platform :ios, '8.0'

target 'ZLHTTPSessionManager_Example' do
  pod 'ZLHTTPSessionManager', :path => '../'

  target 'ZLHTTPSessionManager_Tests' do
    inherit! :search_paths

    
  end
end
